### ISSUE TITLE
Link metadata not petition dependent

### ISSUE THREAD

**Issue by Jack-Papel-RIT** [ritstudentgovernment/PawPrints-Archive#145]
Re-issue of #73, which was closed as resolved, however has not actually been implemented.
According to the replies on the issue, it was added by #76, but in reality the embed doesn't contain any metadata related to the petition shared.

As you can see in this screenshot:
![image](https://user-images.githubusercontent.com/113364195/216431461-0fcf04c5-2322-4ed1-b6a5-aace3f625a73.png)
The embed doesn't have any data about the petition.

**Comment by MoralCode** [comment]
looking at #76 it seems to me like this was implemented by adding a separate endpoint for bots that the nginx server (which at quick search doesnt seem to have its config in this repo) would redirect the crawlers to so the opengraph tags get displayed.

To me it seems like this was done because, when you visit a link such as the one you demonstrated, the pawprint displays as a popup (i.e. the HTML markup is always there, its just hidden when it should be displayed), not its own separate page, so the metadata can become weird if another pawprint is thenn opened, but i guess to a bot this isnt a problem.

ill look into this a little more

**Comment by MoralCode** [comment]
it appears as though the pull request you mentioned is actually implemented but it only works for a specific url in the old format. see screenshot using the current live pawprints.rit.edu site

![Screenshot_20230301_121728](https://user-images.githubusercontent.com/17362949/222213758-a7293f2a-dd3e-4325-a7c9-1035e9963545.png)

as far as i can tell the server side is not involved in the process of fetching a pawprint when a https://pawprints.rit.edu/?p=3525 url is used, that is fetched and displayed by frontend JS.

**Comment by Jack-Papel** [comment]
Just tested it and it still doesn't appear to work. Is the change live?

**Comment by Sma-Das** [comment]
Not live yet
